### PR TITLE
NSynth MaxForLive plugin grid generation

### PR DESCRIPTION
**Pull request by JCBrouwer**
Hello,

I've adapted the [Open NSynth Audio generation pipeline](https://github.com/googlecreativelab/open-nsynth-super/tree/master/audio) to generate grids/multigrids that can be used with the NSynth MaxForLive device.

I haven't been able to test it on multiple GPUs (I've only got 1) or with python3 (recompiling CUDA enabled tensorflow on macOS is quite a lot of work...), but I'm fairly sure they should work.

I also wasn't sure how exactly the Apache 2.0 license works in this case, so I've just copied the license statement that was at the top of the files in the repository linked above. Is the short statement at the top of generate.py about the changes made sufficient?

I've uploaded an example multigrid, generated with the included default settings, [here](https://drive.google.com/open?id=1Z6SqLh_-iha5C4WyEn_vg7cIDaUZyEXs).

### CODE REVIEW

**Comment by jesseengel** [comment]
Thanks for doing this. Sorry I'm a bit delayed in reviewing, I do intend to give it a review when I catch up. Thank you for your patience.

**Comment by JCBrouwer** [comment]
Alright, I changed up the whitespace to be 2 space indentations, added options for batch_sizes, and switched the magenta_dir option to checkpoint_dir.

I updated the README to reflect the changes and added a note about running generate.py from the madenta-demos/nsynth directory.

**Comment by trinitronx** [comment]
Sorry if this isn't the right place to ask a question, but this looks awesome!  Since learning of NSynth and Magenta projects, I've been interested in generating grids for a while.  Does this require a GPU with tensor cores (e.g.: newer Nvidia RTX series?)

**Comment by jesseengel** [comment]
Hi @JCBrouwer, could you take a look at this issue someone is having with the generation code? https://github.com/tensorflow/magenta-demos/issues/63

**Pull request merged**
